spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/stickers?authSource=admin
http:
  bg-removal:
    base-url: http://localhost:8090
  face-swap:
    base-url: http://localhost:8091


